version: "3"

services:
  database:
    container_name: python_flask_db
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: python
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: employee
    healthcheck:
      test: ["cmd", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 3s
      retries: 5
      start_period: 30s

  my_python_flask_assignment:
    image: 1chance/my_python_flask_new_assignment
    restart: always
    ports:
      - 5000:5000
    links:
      - database:dbserver
    depends_on:
      database:
        condition: service_healthy
