version: "3"

services:
  database:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    ports:
      - 32000:3306
    restart: always
    environment:
      MYSQL_USER: python
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: employee
    container_name: python_flask_db

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - database

  my_python_flask_assignment:
    image: 1chance/my_python_flask_assignment
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - database
